---
- name: create users from csv file
  hosts: admin_node

  tasks:
    - name: reading the csv file
      read_csv:
        path: user-create.csv
      register: user_list
      delegate_to: localhost

    - name: Generate line
      command: wbinfo -i {{ item.Username }}
      register: passwd_line
      loop: "{{ user_list.list }}"
      changed_when: False
      ignore_errors: True

    - name: Find full name of user
      shell: "ldapsearch -L -xxx uid={{ item.Username }} | grep ^displayName: | sed 's/displayName: //' | uniq"
      register: user_fullname
      args:
        warn: false
      loop: "{{ user_list.list }}"
      changed_when: False
      ignore_errors: True

    - name: Display full passwd line
      debug:
        msg: "{{ passwd_line }}"
      loop: "{{ user_list.list }}"
      changed_when: False
      ignore_errors: True

    - name: check if groups already exist or not
      command: wbinfo --group-info {{ item.Groups }}
      register: check_ad_output
      loop: "{{ user_list.list }}"
      changed_when: False
      ignore_errors: True

    - name: Fail if group does not exist in AD
      debug: var=check_ad_output.stderr_lines
      when: "'WBC_ERR_DOMAIN_NOT_FOUND' in check_ad_output.stderr_lines"